framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  session: true
  php_errors:
    log: true
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 0
    routing:
      App\Message\AnalyzeTrainingSession: async

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
