<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260817010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add question segments and millisecond timecodes to training sessions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE training_session_segment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, training_session_id INT NOT NULL, question_id INT DEFAULT NULL, position SMALLINT NOT NULL, question_title VARCHAR(500) NOT NULL, category_label VARCHAR(80) NOT NULL, started_at_ms INT NOT NULL, ended_at_ms INT NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF0ECE04DB8156B9 ON training_session_segment (training_session_id)');
        $this->addSql('CREATE INDEX IDX_BF0ECE041E27F6BF ON training_session_segment (question_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_segment_position ON training_session_segment (training_session_id, position)');
        $this->addSql('ALTER TABLE training_session_segment ADD CONSTRAINT FK_A0AC91278971B2B1 FOREIGN KEY (training_session_id) REFERENCES training_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE training_session_segment ADD CONSTRAINT FK_A0AC91271E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE training_session_segment');
    }
}
