<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260819000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add local transcription, AI evaluation and question rubrics';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE training_session ADD analysis_status VARCHAR(20) DEFAULT 'not_started' NOT NULL");
        $this->addSql('ALTER TABLE training_session ADD analysis_score SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE training_session ADD analysis_error_code VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE training_session ADD analysis_error_message TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE training_session ADD analysis_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE training_session ADD analysis_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->addSql('CREATE TABLE question_evaluation_rubric (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question_id INT NOT NULL, reference_answer TEXT NOT NULL, required_points JSON NOT NULL, common_mistakes JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_27F622BB1E27F6BF ON question_evaluation_rubric (question_id)');
        $this->addSql('ALTER TABLE question_evaluation_rubric ADD CONSTRAINT FK_RUBRIC_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE training_session_transcript (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, segment_id INT NOT NULL, model VARCHAR(120) NOT NULL, text TEXT NOT NULL, words JSON NOT NULL, pauses JSON NOT NULL, metrics JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A056C7FADB296AAD ON training_session_transcript (segment_id)');
        $this->addSql('ALTER TABLE training_session_transcript ADD CONSTRAINT FK_TRANSCRIPT_SEGMENT FOREIGN KEY (segment_id) REFERENCES training_session_segment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE training_session_evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, segment_id INT NOT NULL, provider VARCHAR(50) NOT NULL, model VARCHAR(120) NOT NULL, attempts SMALLINT NOT NULL, total_score SMALLINT NOT NULL, criteria JSON NOT NULL, verdict TEXT NOT NULL, strengths JSON NOT NULL, recommendations JSON NOT NULL, missing_topics JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B83754CDB296AAD ON training_session_evaluation (segment_id)');
        $this->addSql('ALTER TABLE training_session_evaluation ADD CONSTRAINT FK_EVALUATION_SEGMENT FOREIGN KEY (segment_id) REFERENCES training_session_segment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $rubrics = [
            ['Чем отличаются require, include и их варианты с _once?', 'include подключает файл и при ошибке выдаёт предупреждение, позволяя скрипту продолжить работу. require при невозможности подключения приводит к ошибке и останавливает текущий сценарий. Варианты include_once и require_once дополнительно предотвращают повторное подключение одного и того же файла.', ['Различие поведения при ошибке', 'Назначение суффикса _once', 'Практический выбор require для обязательных зависимостей'], ['Утверждать, что include и require полностью взаимозаменяемы', 'Считать _once механизмом кеширования содержимого']],
            ['Как устроен жизненный цикл HTTP-запроса в Symfony?', 'Запрос попадает во front controller public/index.php, создаётся Kernel и объект Request передаётся HttpKernel. События kernel.request позволяют изменить запрос, Router находит маршрут, ControllerResolver и ArgumentResolver выбирают контроллер и аргументы. Контроллер возвращает Response, после чего проходят kernel.response, отправка ответа и kernel.terminate.', ['Front controller и Kernel', 'Маршрутизация и выбор контроллера', 'Создание и отправка Response', 'Ключевые события HttpKernel'], ['Пропускать роль HttpKernel', 'Смешивать middleware других фреймворков с событиями Symfony']],
            ['Когда индекс не будет использован оптимизатором MySQL?', 'Оптимизатор может отказаться от индекса при низкой селективности или маленькой таблице, отсутствии ведущей колонки составного индекса, функции или несовместимом приведении типа над индексированным полем, ведущем шаблоне LIKE, невыгодном диапазоне и устаревшей статистике. Решение подтверждают через EXPLAIN, а не по одному правилу.', ['Селективность и стоимость плана', 'Левая часть составного индекса', 'Функции, преобразования типов и LIKE', 'Проверка через EXPLAIN'], ['Гарантировать использование индекса по факту его наличия', 'Игнорировать порядок колонок составного индекса']],
            ['В чём разница между композицией и наследованием?', 'Наследование выражает отношение «является» и связывает подкласс с контрактом и реализацией базового класса. Композиция выражает «содержит» и делегирует работу отдельным объектам. Композиция обычно уменьшает связанность и позволяет менять поведение во время выполнения; наследование уместно при стабильной подстановке по Лисков.', ['Отношения «является» и «содержит»', 'Связанность и замена поведения', 'Принцип подстановки Лисков', 'Практический пример'], ['Представлять композицию только как синтаксический приём', 'Использовать наследование лишь ради повторного использования кода']],
            ['Какие границы ответственности у Repository и Service?', 'Repository инкапсулирует получение и сохранение агрегатов и скрывает детали хранилища. Доменный или прикладной Service координирует бизнес-операцию, правила и взаимодействие нескольких зависимостей. Repository не должен становиться местом бизнес-сценариев, а Service не должен содержать SQL и детали ORM.', ['Repository отвечает за доступ к данным', 'Service отвечает за бизнес-сценарий', 'Разделение деталей ORM и правил', 'Транзакционные границы'], ['Помещать любую логику в Repository', 'Делать Service простой обёрткой над каждым методом ORM']],
            ['Что такое позднее статическое связывание?', 'Позднее статическое связывание в PHP сохраняет класс, из которого был сделан статический вызов. static:: разрешается относительно вызывающего класса и поддерживает наследование, тогда как self:: привязан к классу, где написан метод. Получить вызывающий класс можно через static::class или get_called_class().', ['Различие static:: и self::', 'Связь с наследованием', 'Пример переопределения статического метода'], ['Смешивать с динамическим созданием обычных объектов', 'Утверждать, что self:: выбирает дочерний класс']],
            ['Как работает контейнер зависимостей и autowiring?', 'Контейнер Symfony строит определения сервисов, разрешает зависимости и компилируется в оптимизированный PHP-код. Autowiring сопоставляет типизированные аргументы конструктора с сервисами или алиасами. Неоднозначности решаются явными alias или bind, скаляры задаются конфигурацией. Большинство сервисов приватные и создаются лениво по необходимости.', ['Определения и компиляция контейнера', 'Сопоставление по типам', 'Alias, bind и явная конфигурация', 'Приватность сервисов'], ['Называть autowiring runtime-reflection на каждый запрос', 'Ожидать автоматического разрешения любых scalar-аргументов']],
            ['Что именно проверяет интеграционный тест?', 'Интеграционный тест проверяет совместную работу нескольких реальных компонентов и корректность их контрактов: например контроллера, контейнера, ORM и базы данных. Он отличается от unit-теста шириной границы и от end-to-end теста тем, что не обязан проходить весь пользовательский путь через внешний интерфейс.', ['Совместная работа компонентов', 'Реальные инфраструктурные границы', 'Отличие от unit и end-to-end', 'Изоляция и воспроизводимость окружения'], ['Считать любой тест с моками интеграционным', 'Путать интеграционный и полный UI end-to-end тест']],
        ];

        foreach ($rubrics as [$title, $answer, $points, $mistakes]) {
            $this->addSql(
                'INSERT INTO question_evaluation_rubric (question_id, reference_answer, required_points, common_mistakes) SELECT id, ?, ?::json, ?::json FROM question WHERE title = ? ON CONFLICT (question_id) DO NOTHING',
                [$answer, json_encode($points, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR), json_encode($mistakes, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR), $title],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE training_session_evaluation');
        $this->addSql('DROP TABLE training_session_transcript');
        $this->addSql('DROP TABLE question_evaluation_rubric');
        $this->addSql('ALTER TABLE training_session DROP analysis_status');
        $this->addSql('ALTER TABLE training_session DROP analysis_score');
        $this->addSql('ALTER TABLE training_session DROP analysis_error_code');
        $this->addSql('ALTER TABLE training_session DROP analysis_error_message');
        $this->addSql('ALTER TABLE training_session DROP analysis_started_at');
        $this->addSql('ALTER TABLE training_session DROP analysis_completed_at');
    }
}
