<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260817000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create interview trainer tables and initial data';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(50) NOT NULL, category_label VARCHAR(80) NOT NULL, category_color VARCHAR(7) NOT NULL, title VARCHAR(500) NOT NULL, level VARCHAR(30) NOT NULL, memory SMALLINT DEFAULT 0 NOT NULL, repeats SMALLINT DEFAULT 0 NOT NULL, hint TEXT NOT NULL, last_answered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, best_score SMALLINT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE training_question (training_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY(training_id, question_id))');
        $this->addSql('CREATE INDEX IDX_51925AD9BEFD98D1 ON training_question (training_id)');
        $this->addSql('CREATE INDEX IDX_51925AD91E27F6BF ON training_question (question_id)');
        $this->addSql('ALTER TABLE training_question ADD CONSTRAINT FK_TQ_TRAINING FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE training_question ADD CONSTRAINT FK_TQ_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE training_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, training_id INT NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, elapsed_seconds INT DEFAULT 0 NOT NULL, answered_count SMALLINT DEFAULT 0 NOT NULL, score SMALLINT DEFAULT NULL, audio_filename VARCHAR(180) DEFAULT NULL, audio_mime_type VARCHAR(80) DEFAULT NULL, audio_size INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D7A45DABEFD98D1 ON training_session (training_id)');
        $this->addSql('ALTER TABLE training_session ADD CONSTRAINT FK_TS_TRAINING FOREIGN KEY (training_id) REFERENCES training (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $hint = 'Начните с определения, затем объясните механизм на примере и обязательно назовите практические ограничения.';
        $questions = [
            ['php', 'PHP', '#7168a8', 'Чем отличаются require, include и их варианты с _once?', 'Базовый', 92, 4],
            ['symfony', 'Symfony', '#171717', 'Как устроен жизненный цикл HTTP-запроса в Symfony?', 'Средний', 68, 3],
            ['mysql', 'MySQL', '#e48a28', 'Когда индекс не будет использован оптимизатором MySQL?', 'Средний', 41, 2],
            ['oop', 'ООП', '#3f8065', 'В чём разница между композицией и наследованием?', 'Базовый', 84, 5],
            ['architecture', 'Архитектура', '#bb564e', 'Какие границы ответственности у Repository и Service?', 'Продвинутый', 22, 1],
            ['php', 'PHP', '#7168a8', 'Что такое позднее статическое связывание?', 'Средний', 57, 2],
            ['symfony', 'Symfony', '#171717', 'Как работает контейнер зависимостей и autowiring?', 'Средний', 73, 4],
            ['testing', 'Тестирование', '#397f9c', 'Что именно проверяет интеграционный тест?', 'Базовый', 35, 1],
        ];
        foreach ($questions as $question) {
            $this->addSql(
                'INSERT INTO question (category, category_label, category_color, title, level, memory, repeats, hint, last_answered_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW() - INTERVAL \'2 days\', NOW())',
                [...$question, $hint],
            );
        }
        $this->addSql("INSERT INTO training (name, best_score, created_at, updated_at) VALUES ('PHP Backend — пробное собеседование', NULL, NOW(), NOW())");
        $this->addSql('INSERT INTO training_question (training_id, question_id) SELECT 1, id FROM question WHERE id IN (2, 3, 5)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE training_session');
        $this->addSql('DROP TABLE training_question');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE question');
    }
}
